### ISSUE TITLE
感谢您的代码提供了思路

### ISSUE THREAD

**Issue by YangYueFan** [mengxianliang/XLDouYinLoading#1]
感谢您的代码提供了思路
其次  你代码还可以优化了下
1、某个球添加黑球的时候  应该一开始就添加  然后在改变方向的时候去添加
而不是一直添加
2、更新黑球位置(大小)应该放在放大缩小动画之后   这样黑球可以不用使用动画 

这样减少了代码 又节省点资源

**Comment by mengxianliang** [comment]
感谢指出问题，已经改好了。
